version: "3"
services:
  db:
    # 起動するイメージを指定
    image: mysql:8.0.23

    env_file: .env

    # 環境変数を設定
    environment:
      - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOS}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      - TZ=${TZ}

    # ホスト側のポート:コンテナのポート
    ports:
      - "3307:3306"

    # ボリュームバインド
    volumes:
      - ./db/conf:/etc/mysql/conf.d/:ro
      - mysqldata:/var/lib/mysql
      - ./db/logs:/var/log/mysql

    #使用するネットワーク
    # networks:
    #   - backend

  api:
    build:
      context: ./api
    env_file: .env
    image: node-api-image
    environment:
      - MYSQL_SERVER=db
      - MYSQL_USER=${MYSQL_ROOT_HOST}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=${TZ}
      - DATABASE_URL=${DATABASE_URL}
      - CHOKIDAR_USEPOLLING=true

    #コンテナを起動させ続けるよう設定
    tty: true

    ports:
      - "3000:8000"

    # ソースコードを格納するフォルダをマウント
    #（ホスト側の./apiをコンテナの/appにマウント）
    volumes:
      - ./api:/app

    # 起動時のカレントフォルダを指定
    working_dir: /app

    # 起動後に実行するコマンドを指定
    command: bash -c "npm install &&
      npm install nodemon -g &&
      nodemon src/server.js"

    # networks:
    #   - backend

    #依存関係（apiコンテナより先にdbコンテナが起動するように設定）
    depends_on:
      - db

# networks:
#   backend:

volumes:
  mysqldata:
